In [ ]:
#Artificial Intelligence
#LAB ESE Experiment List
#1.Implement Non-AI Techniques for Tic-Tac-Toe the problem.
#2.Implement Non-AI Techniques for N-Queens the problem.
#3.Implement Non-AI Techniques for Magic Square the problem.
#4.Implement the Water Jug problem using Depth First Search
#5.mplement the Water Jug problem using Breadth First Search
#6.Implement the Hill Climbing technique to solve the 8 puzzle problem.
#7.Implement 8 Puzzle problem using Best First Search Algorithm
#8.Implement Cities Distance (shortest path) problem using Best First Search Algorithm
#9.Implement 8 Puzzle problem using A* Algorithm
#10. Implement Cities Distance (shortest path) problem using A* Algorithm
#11. Implement the Minimax algorithm to solve the Tic Tac Toe problem

In [2]:
#1.Implement Non-AI Techniques for Tic-Tac-Toe the problem.


import random

def create_board():
    return [[" " for _ in range(3)] for _ in range(3)]

def print_board(board):
    for row in board:
        print("|".join(row))
        print("-" * 5)

def check_win(board, player):
    for row in board:
        if all(cell == player for cell in row):
            return True

    for col in range(3):
        if all(board[row][col] == player for row in range(3)):
            return True

    if all(board[i][i] == player for i in range(3)):
        return True 
    if all(board[i][2-i] == player for i in range(3)):
        return True

    return False

def check_draw(board):
    return all(cell!= " " for row in board for cell in row)


def make_move(board, player):
    while True:
        try:
            row = int(input(f"Enter row (0-2) for {player}: "))
            col = int(input(f"Enter column (0-2) for {player}: "))
            if board[row][col] == " ":
                board[row][col] = player
                break
            else:
                print("Cell already taken, choose again.")
        except (ValueError, IndexError):
            print("Invalid input, please enter numbers between 0 and 2.")


def bot_move(board, player):
    available = [(i,j) for i in range(3) for j in range(3) if board[i][j] == " "]
    move = random.choice(available)
    board[move[0]][move[1]] = player

def play_game():
    board = create_board()
    mode=input("play against (1) another player or (2) bot? Enter 1 or 2: ").strip()
    current_player = "X"

    while True:
        print_board(board)

        if mode == "1" or (mode == "2" and current_player == "X"):
            make_move(board, current_player)
        else:
            print(f"Bot ({current_player}) is making a move...")
            bot_move(board, current_player)

        if check_win(board, current_player):
            print_board(board)
            print(f"Player {current_player} wins!")
            break
        elif check_draw(board):
            print_board(board)
            print("It's a draw!")
            break

        current_player = "O" if current_player == "X" else "X"

if __name__ == "__main__":
    play_game()

play against (1) another player or (2) bot? Enter 1 or 2:  2


 | | 
-----
 | | 
-----
 | | 
-----


Enter row (0-2) for X:  0
Enter column (0-2) for X:  0


X| | 
-----
 | | 
-----
 | | 
-----
Bot (O) is making a move...
X| | 
-----
 | | 
-----
O| | 
-----


Enter row (0-2) for X:  1
Enter column (0-2) for X:  2


X| | 
-----
 | |X
-----
O| | 
-----
Bot (O) is making a move...
X|O| 
-----
 | |X
-----
O| | 
-----


Enter row (0-2) for X:  1
Enter column (0-2) for X:  1


X|O| 
-----
 |X|X
-----
O| | 
-----
Bot (O) is making a move...
X|O| 
-----
O|X|X
-----
O| | 
-----


Enter row (0-2) for X:  2
Enter column (0-2) for X:  2


X|O| 
-----
O|X|X
-----
O| |X
-----
Player X wins!


In [1]:
#2.Implement Non-AI Techniques for N-Queens the problem.


def print_board(board, n):
    for i in range(n):
        row = ""
        for j in range(n):
            if board[i][j] == 1:
                row += "Q "
            else:
                row += ". "
        print(row)
    print()

def is_safe(board, row, col, n):
    # Check column
    for i in range(row):
        if board[i][col] == 1:
            return False

    # Check upper-left diagonal
    i, j = row, col
    while i >= 0 and j >= 0:
        if board[i][j] == 1:
            return False
        i -= 1
        j -= 1

    # Check upper-right diagonal
    i, j = row, col
    while i >= 0 and j < n:
        if board[i][j] == 1:
            return False
        i -= 1
        j += 1

    return True

def solve_n_queens(board, row, n):
    if row == n:
        print_board(board, n)
        return True

    res = False
    for col in range(n):
        if is_safe(board, row, col, n):
            board[row][col] = 1
            res = solve_n_queens(board, row + 1, n) or res
            board[row][col] = 0  # Backtrack

    return res

def n_queens(n):
    board = [[0 for _ in range(n)] for _ in range(n)]
    if not solve_n_queens(board, 0, n):
        print("No solution exists.")

if __name__ == "__main__":
    n = int(input("Enter the value of N: "))
    n_queens(n)


Enter the value of N:  4


. Q . . 
. . . Q 
Q . . . 
. . Q . 

. . Q . 
Q . . . 
. . . Q 
. Q . . 



In [3]:
#3.Implement Non-AI Techniques for Magic Square the problem.

def generate_magic_square(n):
    if n % 2 == 0:
        print("This method works only for odd-sized magic squares.")
        return

    magic_square = [[0] * n for _ in range(n)]

    # Start position at middle of top row
    row, col = 0, n // 2

    for num in range(1, n * n + 1):
        magic_square[row][col] = num

        # Compute next row and column
        new_row, new_col = (row - 1) % n, (col + 1) % n

        # If occupied, move downward
        if magic_square[new_row][new_col]:
            row += 1
        else:
            row, col = new_row, new_col

    # Print magic square
    for row in magic_square:
        print(" ".join(str(num) for num in row))

# Input from user
N = int(input("Enter an odd number for magic square size: "))
generate_magic_square(N)


Enter an odd number for magic square size:  3


8 1 6
3 5 7
4 9 2


In [4]:
#4.Implement the Water Jug problem using Depth First Search

def water_jug_dfs(capacity_a, capacity_b, target):
    stack = [(0, 0)]  # Initial state (0,0)
    visited = set()
    path = []  # To store the solution path

    while stack:
        state = stack.pop()
        a, b = state

        # If the state is already visited, skip
        if state in visited:
            continue

        # Mark the state as visited and store the path
        visited.add(state)
        path.append(state)

        # Check if we have reached the goal state
        if a == target or b == target:
            return path

        # Generate possible next states
        next_states = [
            (capacity_a, b),  # Fill Jug A
            (a, capacity_b),  # Fill Jug B
            (0, b),  # Empty Jug A
            (a, 0),  # Empty Jug B
            (a - min(a, capacity_b - b), b + min(a, capacity_b - b)),  # Pour A -> B
            (a + min(b, capacity_a - a), b - min(b, capacity_a - a))   # Pour B -> A
        ]

        #Add new states to the stack if they haven't been visited
        for new_state in next_states:
            if new_state not in visited:
                stack.append(new_state)
    
    return None  # No solution

if __name__ == "__main__":
    # Take user input
    capacity_a = int(input("Enter the capacity of Jug A: "))  # Capacity of Jug A
    capacity_b = int(input("Enter the capacity of Jug B: "))  # Capacity of Jug B
    target = int(input("Enter the target amount of water: "))  # Target amount of water

    solution = water_jug_dfs(capacity_a, capacity_b, target)

    # Display the solution path
    if solution:
        print("Solution Path:")
        for state in solution:
            print(f"Jug A: {state[0]}, Jug B: {state[1]}")
    else:
        print("No solution found.")


Enter the capacity of Jug A:  4
Enter the capacity of Jug B:  3
Enter the target amount of water:  2


Solution Path:
Jug A: 0, Jug B: 0
Jug A: 0, Jug B: 3
Jug A: 3, Jug B: 0
Jug A: 3, Jug B: 3
Jug A: 4, Jug B: 2


In [5]:
#5.Implement the Water Jug problem using Breadth First Search


from collections import deque

def bfs_water_jug(capacity_a, capacity_b, target):
    initial_state = (0, 0)  # Both jugs start empty
    queue = deque([initial_state])  # BFS queue
    visited = set([initial_state])  # Track visited states
    parent = {initial_state: None}  # Track the path

    while queue:
        a, b = queue.popleft()

        # If either jug contains the target amount, reconstruct path
        if a == target or b == target:
            return reconstruct_path(parent, (a, b))

        # Possible actions
        next_states = [
            (capacity_a, b),  # Fill Jug A
            (a, capacity_b),  # Fill Jug B
            (0, b),  # Empty Jug A
            (a, 0),  # Empty Jug B
            (a - min(a, capacity_b - b), b + min(a, capacity_b - b)),  # Pour A → B
            (a + min(b, capacity_a - a), b - min(b, capacity_a - a))   # Pour B → A
        ]

        for new_state in next_states:
            if new_state not in visited:
                visited.add(new_state)
                queue.append(new_state)
                parent[new_state] = (a, b)  # Store path

    return None  # No solution found

def reconstruct_path(parent, state):
    path = []
    while state is not None:  # Trace back to the start
        path.append(state)
        state = parent[state]
    return path[::-1]  # Reverse for correct order

# Example usage with user input
if __name__ == "__main__":
    # Take user input for jug capacities and target
    capacity_a = int(input("Enter the capacity of Jug A: "))  # Capacity of Jug A
    capacity_b = int(input("Enter the capacity of Jug B: "))  # Capacity of Jug B
    target = int(input("Enter the target amount of water: "))  # Target amount of water

    solution = bfs_water_jug(capacity_a, capacity_b, target)

    # Display the solution path
    if solution:
        print("Steps to reach the goal:")
        for step in solution:
            print(f"Jug A: {step[0]}, Jug B: {step[1]}")
    else:
        print("No solution found.")


Enter the capacity of Jug A:  4
Enter the capacity of Jug B:  3
Enter the target amount of water:  2


Steps to reach the goal:
Jug A: 0, Jug B: 0
Jug A: 0, Jug B: 3
Jug A: 3, Jug B: 0
Jug A: 3, Jug B: 3
Jug A: 4, Jug B: 2


In [13]:
import random
import copy

class Puzzle:
    def __init__(self, board):
        self.board = board
        self.size = 3  # 3x3 puzzle
        self.goal = [[1, 2, 3], [4, 5, 6], [7, 8, 0]]

    def get_empty_tile(self):
        for i in range(self.size):
            for j in range(self.size):
                if self.board[i][j] == 0:
                    return i, j

    def get_neighbors(self):
        neighbors = []
        row, col = self.get_empty_tile()
        moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]  # up, down, left, right

        for dr, dc in moves:
            new_row, new_col = row + dr, col + dc
            if 0 <= new_row < self.size and 0 <= new_col < self.size:
                new_board = copy.deepcopy(self.board)
                new_board[row][col], new_board[new_row][new_col] = new_board[new_row][new_col], new_board[row][col]
                neighbors.append(Puzzle(new_board))

        return neighbors

    def heuristic(self):
        # Number of misplaced tiles (excluding 0)
        return sum(
            1
            for i in range(self.size)
            for j in range(self.size)
            if self.board[i][j] != 0 and self.board[i][j] != self.goal[i][j]
        )

    def print_board(self):
        for row in self.board:
            print(row)
        print()

    def hill_climbing(self):
        current = self
        step = 0
        while True:
            print(f"Step {step}: Heuristic = {current.heuristic()}")
            current.print_board()
            step += 1

            neighbors = current.get_neighbors()
            best_neighbor = min(neighbors, key=lambda x: x.heuristic(), default=None)

            if best_neighbor is None or best_neighbor.heuristic() >= current.heuristic():
                print("Reached local optimum or goal.\n")
                return current  # Local optimum reached

            current = best_neighbor


def main():
    initial_state = [[1, 0, 3], [4, 2, 6], [7, 5, 8]]  # Example starting board
    puzzle = Puzzle(initial_state)
    print("Initial State:")
    puzzle.print_board()

    solution = puzzle.hill_climbing()
    print("Final State:")
    solution.print_board()


if __name__ == "__main__":
    main()




Initial State:
[1, 0, 3]
[4, 2, 6]
[7, 5, 8]

Step 0: Heuristic = 3
[1, 0, 3]
[4, 2, 6]
[7, 5, 8]

Step 1: Heuristic = 2
[1, 2, 3]
[4, 0, 6]
[7, 5, 8]

Step 2: Heuristic = 1
[1, 2, 3]
[4, 5, 6]
[7, 0, 8]

Step 3: Heuristic = 0
[1, 2, 3]
[4, 5, 6]
[7, 8, 0]

Reached local optimum or goal.

Final State:
[1, 2, 3]
[4, 5, 6]
[7, 8, 0]



In [16]:
#7.Implement 8 Puzzle problem using Best First Search Algorithm

import heapq

GOAL = [[1, 2, 3], [4, 5, 6], [7, 8, 0]]

def heuristic(state): return sum(state[i][j] != GOAL[i][j] and state[i][j] != 0 for i in range(3) for j in range(3))

def find_blank(state): return next((i, j) for i in range(3) for j in range(3) if state[i][j] == 0)

def neighbors(state):
    i, j = find_blank(state)
    moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    return [swap(state, i, j, i + di, j + dj) for di, dj in moves if 0 <= i + di < 3 and 0 <= j + dj < 3]

def swap(state, i1, j1, i2, j2):
    new_state = [row[:] for row in state]
    new_state[i1][j1], new_state[i2][j2] = new_state[i2][j2], new_state[i1][j1]
    return new_state

def best_first_search(start):
    frontier, visited = [(heuristic(start), start)], set()
    while frontier:
        _, state = heapq.heappop(frontier)
        if state == GOAL: return state
        visited.add(str(state))
        for neighbor in neighbors(state):
            if str(neighbor) not in visited: heapq.heappush(frontier, (heuristic(neighbor), neighbor))

start_state = [[1, 2, 3], [4, 0, 5], [7, 8, 6]]
solution = best_first_search(start_state)

print("Solution Found:\n", *solution, sep="\n") if solution else print("No solution found.")



Solution Found:

[1, 2, 3]
[4, 5, 6]
[7, 8, 0]


In [17]:
#8.Implement Cities Distance (shortest path) problem using Best First Search Algorithm

import heapq

# Example graph with heuristic estimates
graph = {
    'A': [('B', 10), ('C', 3)],
    'B': [('D', 2)],
    'C': [('D', 8), ('E', 2)],
    'D': [('F', 6)],
    'E': [('F', 4)],
    'F': []
}

# Heuristic (Estimated Distance to Goal)
heuristic = {
    'A': 7, 'B': 6, 'C': 4, 'D': 3, 'E': 2, 'F': 0  # Goal is 'F'
}

def best_first_search(start, goal):
    """Best-First Search Algorithm"""
    priority_queue = []
    heapq.heappush(priority_queue, (heuristic[start], start))  # Push start city with heuristic cost
    visited = set()
    path = []

    while priority_queue:
        _, current_city = heapq.heappop(priority_queue)  # Get city with lowest heuristic
        path.append(current_city)

        if current_city == goal:
            print(f"Shortest path: {' → '.join(path)}")
            return path

        visited.add(current_city)

        for neighbor, cost in graph[current_city]:  # Explore neighbors
            if neighbor not in visited:
                heapq.heappush(priority_queue, (heuristic[neighbor], neighbor))

    print("No path found.")
    return None

# Example usage
start_city = 'A'
goal_city = 'F'
best_first_search(start_city, goal_city)


Shortest path: A → C → E → F


['A', 'C', 'E', 'F']

In [25]:
#9.Implement 8 Puzzle problem using A* Algorithm


import heapq
import numpy as np

class PuzzleNode:
    def __init__(self, state, parent, move, depth, cost):
        self.state = state
        self.parent = parent
        self.move = move
        self.depth = depth
        self.cost = cost

    def __lt__(self, other):
        # Compare nodes based on the total cost (cost + depth)
        return (self.cost + self.depth) < (other.cost + other.depth)

# Heuristic function: Manhattan Distance
def manhattan_distance(state, goal):
    distance = 0
    for i in range(3):
        for j in range(3):
            if state[i][j] != 0:
                x, y = np.where(goal == state[i][j])
                distance += abs(i - x[0]) + abs(j - y[0])
    return distance

# A* for 8-puzzle
def a_star_8_puzzle(start, goal):
    goal = np.array(goal)
    frontier = []
    heapq.heappush(frontier, PuzzleNode(start, None, None, 0, manhattan_distance(start, goal)))
    explored = set()
    
    while frontier:
        node = heapq.heappop(frontier)
        explored.add(tuple(map(tuple, node.state)))  # Use tuple representation of the state
        
        if np.array_equal(node.state, goal):
            path = []
            while node:
                path.append(node.state)
                node = node.parent
            return path[::-1]  # Return the path in correct order
        
        # Possible moves: up, down, left, right
        moves = [(0, 1), (1, 0), (0, -1), (-1, 0)]
        zero_x, zero_y = np.where(node.state == 0)
        for dx, dy in moves:
            new_x, new_y = zero_x[0] + dx, zero_y[0] + dy
            if 0 <= new_x < 3 and 0 <= new_y < 3:
                new_state = node.state.copy()
                new_state[zero_x[0], zero_y[0]], new_state[new_x, new_y] = new_state[new_x, new_y], new_state[zero_x[0], zero_y[0]]
                if tuple(map(tuple, new_state)) not in explored:
                    heapq.heappush(frontier, PuzzleNode(new_state, node, (dx, dy), node.depth + 1, manhattan_distance(new_state, goal)))
    return None  # No path found

# Example usage
def main():
    start = np.array([[1, 0, 3], [4, 2, 6], [7, 5, 8]])  # Initial state
    goal = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])   # Goal state
    path = a_star_8_puzzle(start, goal)

    if path:
        print("Solution found!")
        for step in path:
            print(f"\n{step}")
    else:
        print("No solution found.")

if __name__ == "__main__":
    main()




Solution found!

[[1 0 3]
 [4 2 6]
 [7 5 8]]

[[1 2 3]
 [4 0 6]
 [7 5 8]]

[[1 2 3]
 [4 5 6]
 [7 0 8]]

[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [26]:
#10. Implement Cities Distance (shortest path) problem using A* Algorithm

import heapq

def a_star(graph, start, goal, heuristic):
    frontier, came_from, cost = [(0, start)], {start: None}, {start: 0}
    
    while frontier:
        _, current = heapq.heappop(frontier)
        if current == goal:
            path = []
            while current: path.append(current); current = came_from[current]
            return path[::-1]
        
        for neighbor, weight in graph[current].items():
            new_cost = cost[current] + weight
            if neighbor not in cost or new_cost < cost[neighbor]:
                cost[neighbor], came_from[neighbor] = new_cost, current
                heapq.heappush(frontier, (new_cost + heuristic(neighbor), neighbor))

def heuristic(city):
    return {'A': 7, 'B': 6, 'C': 2, 'D': 0}.get(city, float('inf'))

graph = {'A': {'B': 2, 'C': 4}, 'B': {'A': 2, 'C': 1, 'D': 7}, 'C': {'A': 4, 'B': 1, 'D': 3}, 'D': {'B': 7, 'C': 3}}
print("Shortest Path:", a_star(graph, 'A', 'D', heuristic))


Shortest Path: ['A', 'C', 'D']


In [ ]:
#11. Implement the Minimax algorithm to solve the Tic Tac Toe problem

import math

def print_board(board):
    for i, row in enumerate(board):
        print(" | ".join(row))
        if i < 2:
            print("----------")

def check_winner(board):
    lines = board + list(map(list, zip(*board))) + [
        [board[i][i] for i in range(3)],
        [board[i][2 - i] for i in range(3)],
    ]
    for line in lines:
        if line == ["X"] * 3:
            return "X"
        elif line == ["O"] * 3:
            return "O"
    if all(cell != " " for row in board for cell in row):
        return "Draw"
    return None

def minimax(board, is_maximizing):
    winner = check_winner(board)
    if winner == "X":
        return 1
    elif winner == "O":
        return -1
    elif winner == "Draw":
        return 0

    if is_maximizing:
        best_score = -math.inf
        for i in range(3):
            for j in range(3):
                if board[i][j] == " ":
                    board[i][j] = "X"
                    score = minimax(board, False)
                    board[i][j] = " "
                    best_score = max(score, best_score)
        return best_score
    else:
        best_score = math.inf
        for i in range(3):
            for j in range(3):
                if board[i][j] == " ":
                    board[i][j] = "O"
                    score = minimax(board, True)
                    board[i][j] = " "
                    best_score = min(score, best_score)
        return best_score

def best_move(board):
    best_score = -math.inf
    move = None
    for i in range(3):
        for j in range(3):
            if board[i][j] == " ":
                board[i][j] = "X"
                score = minimax(board, False)
                board[i][j] = " "
                if score > best_score:
                    best_score = score
                    move = (i, j)
    return move

def human_vs_ai():
    board = [[" " for _ in range(3)] for _ in range(3)]
    print("You are 'O', AI is 'X'")
    print_board(board)

    while not check_winner(board):
        # Human move
        while True:
            try:
                row = int(input("Enter row (0-2): "))
                col = int(input("Enter col (0-2): "))
                if board[row][col] == " ":
                    board[row][col] = "O"
                    break
                else:
                    print("Cell already taken!")
            except:
                print("Invalid input. Try again.")

        print("\nBoard after your move:")
        print_board(board)
        if check_winner(board):
            break

        # AI move
        ai_move = best_move(board)
        if ai_move:
            board[ai_move[0]][ai_move[1]] = "X"
            print("\nAI moves:")
            print_board(board)

    result = check_winner(board)
    print("\nGame Over! Winner:", result)

if __name__ == "__main__":
    human_vs_ai()


You are 'O', AI is 'X'
  |   |  
----------
  |   |  
----------
  |   |  
